name: Build and Release Flutter App

# This workflow triggers when a new tag is pushed to the main branch.
# Tags should follow a pattern like v1.0.0, v1.2.3, etc.
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.7'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: build/app/outputs/apk/release/app-release.apk
          body: "Automated release for ${{ github.ref_name }}"
